# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuotesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 5.6'

  # Pods for QuotesApp

  target 'QuotesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuotesAppUITests' do
    # Pods for testing
  end

end
